build:
  nodes:
    analysis:
      dependencies:
        after:
          - composer require --dev phalcon/ide-stubs
      tests:
        override:
          - php-scrutinizer-run

  tests:
    override:
      - command: phpcs-run
      - command: vendor/bin/codecept run --coverage-xml
        coverage:
          file: 'tests/_output/coverage.xml'
          format: 'clover'

  dependencies:
    before:
      - cp storage/setup/.env.example .env
      - sed -i -re 's|^APP_ENV=.*|APP_ENV=testing|g' .env
      - sudo -u scrutinizer composer self-update
      - sudo -u scrutinizer cp storage/setup/nginx.conf /etc/nginx/sites-enabled/docs-app
      - sudo -u scrutinizer rm /etc/nginx/sites-enabled/default

filter:
  excluded_paths:
    - 'vendor/*'
    - 'docs/*'
    - 'storage/*'

checks:
  php:
    return_doc_comments: true
    return_doc_comment_if_not_inferrable: true
    parameter_doc_comments: true
    param_doc_comment_if_not_inferrable: true
    optional_parameters_at_the_end: true
    no_short_variable_names:
      minimum: '3'
    no_short_method_names:
      minimum: '3'
    no_long_variable_names:
      maximum: '20'
    line_length:
      max_length: '120'
    no_goto: true
    newline_at_end_of_file: true
    more_specific_types_in_doc_comments: true
    encourage_single_quotes: true
    encourage_postdec_operator: true
    classes_in_camel_caps: true
    avoid_multiple_statements_on_same_line: true
    align_assignments: true
    code_rating: true

build_failure_conditions:
  # No issues of major or higher severity
  # - 'issues.severity(>= MAJOR).exists'

  # Don't let Code Quality Rating drop below 6.
  - 'project.metric("scrutinizer.quality", < 6)'

  # No new coding style issues allowed
  - 'issues.label("coding-style").new.exists'

  # No more than two new classes/methods with a rating of C
  - 'elements.rating(<= C).new.count > 2'

  # No classes/methods with a rating of D or worse.
  # - 'elements.rating(<= D).exists'
