#!/usr/bin/env bash

# trace ERR through pipes
set -o pipefail

# trace ERR through 'time command' and other functions
set -o errtrace

# set -e : exit the script if any statement returns a non-true return value
set -o errexit

CURRENT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

DOCS_REPO=https://github.com/phalcon/docs
CPHALCON_REPO=https://github.com/phalcon/cphalcon

DOCS_PATH="${DOCS_PATH:-${CURRENT_DIR}/docs}"
API_PATH="${API_PATH:-${CURRENT_DIR}/storage/repo}"

ST_OK=0
ST_ERR=1
ST_HLP=2

GREEN="\033[0;32m"
RED="\033[0;31m"
YELLOW="\e[1;33m"
PURPLE="\e[0;35m"
NC="\033[0m"

UPDATE_COMPOSER=0

VERSION=0.2.0

print_version() {
    printf "${YELLOW}Phalcon Docs Deploy Script${NC} v${VERSION}\n"
}

print_help() {
    printf "\n"
    print_version
    printf "\n  Description:"
    printf "\n  Phalcon Docs Deploy Script is a source code deploying script.\n"
    printf "\nUsage: ${PURPLE}./deploy [command]${NC}\n"
    printf "\nCommands:"
    printf "\n  -H | --help                     Show this help message."
    printf "\n  -U | --update-deps              Update dependencies using the Composer."
    printf "\n  -V | --version                  Show the version and exit."
    printf "\n"
}

print_unknown_arg() {
    printf "${RED}Unknow argument: ${1}${NC}\n"
}

while test -n "$1"; do
    case $1 in
        --help|-H)
            print_help
            exit ${ST_HLP}
            ;;
        --version|-V)
            print_version
            exit ${ST_HLP}
            ;;
        --update-deps|-U)
            UPDATE_COMPOSER=1
            ;;
        *)
            print_unknown_arg $1
            exit ${ST_HLP}
            ;;
    esac
    shift
done

ref=$(git rev-parse --abbrev-ref HEAD)

echo -e "Current branch is ${ref}"

if [[ ${ref} != master ]]; then
    echo "Doing nothing: only the master branch may be deployed for this project"
    exit 0
fi

echo -e "Pull the latest changes from the git repo..."
git checkout -f
git pull origin ${ref}

if [[ ! -f "${CURRENT_DIR}/VERSIONS" ]]; then
	echo -e "Unable to locate the VERSIONS file. Exit..."
	exit 1
fi

echo -e ""

while IFS= read -r version; do
    echo -e "Clear the docs folder..."
    rm -rf "${DOCS_PATH}/${version}"
    mkdir -p "${DOCS_PATH}/${version}"

    echo -e "Update the docs for ${version}..."
    echo -e "git clone -q -b ${version} --depth=1 ${DOCS_REPO}" "${DOCS_PATH}/${version}"
    echo -e "Done\n"

    echo -e "Clear the repo folder for ${version}..."
    find ${API_PATH} ! -name '.gitignore' ! -path ${API_PATH}  -exec rm -rf {} \;
    mkdir -p "${API_PATH}"

    echo -e "Clone cphalcon's $version branch..."
    echo -e "TODO: git clone -q -b ${version}.0 --depth=1 ${CPHALCON_REPO} ${API_PATH}"
    echo -e "TODO: regenerate the API doc"
    echo -e "TODO: copy the generated API doc to the ${DOCS_PATH}/${version}/en/api"
    echo -e "Done\n"
done < "${CURRENT_DIR}/VERSIONS"

echo -e "Clear the cache..."
./phalcon -clear-cache
