#!/usr/bin/env php
<?php

use Docs\Cli;
use Phalcon\Di\FactoryDefault\Cli as PhDiCli;

// Register the auto loader
require __DIR__.'/bootstrap/autoloader.php';

try {
    (new Cli())->run(new PhDiCli());
} catch (\Exception $e) {
    fwrite(STDERR, PHP_EOL . $e->getMessage() . PHP_EOL);
    fwrite(STDERR, PHP_EOL . $e->getTraceAsString() . PHP_EOL . PHP_EOL);
    exit(1);
}
