#!/bin/bash

echo "Copying data files...."

cp -v ./4.0/en/meta-home.json           ./_data/4-0-en-meta-home.json
cp -v ./4.0/en/meta-topics.json         ./_data/4-0-en-meta-topics.json
cp -v ./4.0/en/meta-articles.json       ./_data/4-0-en-meta-articles.json
cp -v ./4.0/cs-cz/meta-home.json        ./_data/4-0-cs-cz-meta-home.json
cp -v ./4.0/cs-cz/meta-topics.json      ./_data/4-0-cs-cz-meta-topics.json
cp -v ./4.0/cs-cz/meta-articles.json    ./_data/4-0-cs-cz-meta-articles.json
cp -v ./4.0/el-gr/meta-home.json        ./_data/4-0-el-gr-meta-home.json
cp -v ./4.0/el-gr/meta-topics.json      ./_data/4-0-el-gr-meta-topics.json
cp -v ./4.0/el-gr/meta-articles.json    ./_data/4-0-el-gr-meta-articles.json
cp -v ./4.0/es/meta-home.json           ./_data/4-0-es-meta-home.json
cp -v ./4.0/es/meta-topics.json         ./_data/4-0-es-meta-topics.json
cp -v ./4.0/es/meta-articles.json       ./_data/4-0-es-meta-articles.json
cp -v ./4.0/fa/meta-home.json           ./_data/4-0-fa-meta-home.json
cp -v ./4.0/fa/meta-topics.json         ./_data/4-0-fa-meta-topics.json
cp -v ./4.0/fa/meta-articles.json       ./_data/4-0-fa-meta-articles.json
cp -v ./4.0/fil/meta-home.json          ./_data/4-0-fil-meta-home.json
cp -v ./4.0/fil/meta-topics.json        ./_data/4-0-fil-meta-topics.json
cp -v ./4.0/fil/meta-articles.json      ./_data/4-0-fil-meta-articles.json
cp -v ./4.0/fr/meta-home.json           ./_data/4-0-fr-meta-home.json
cp -v ./4.0/fr/meta-topics.json         ./_data/4-0-fr-meta-topics.json
cp -v ./4.0/fr/meta-articles.json       ./_data/4-0-fr-meta-articles.json
cp -v ./4.0/fr-fr/meta-home.json        ./_data/4-0-fr-fr-meta-home.json
cp -v ./4.0/fr-fr/meta-topics.json      ./_data/4-0-fr-fr-meta-topics.json
cp -v ./4.0/fr-fr/meta-articles.json    ./_data/4-0-fr-fr-meta-articles.json
cp -v ./4.0/hr/meta-home.json           ./_data/4-0-hr-meta-home.json
cp -v ./4.0/hr/meta-topics.json         ./_data/4-0-hr-meta-topics.json
cp -v ./4.0/hr/meta-articles.json       ./_data/4-0-hr-meta-articles.json
cp -v ./4.0/id-id/meta-home.json        ./_data/4-0-id-id-meta-home.json
cp -v ./4.0/id-id/meta-topics.json      ./_data/4-0-id-id-meta-topics.json
cp -v ./4.0/id-id/meta-articles.json    ./_data/4-0-id-id-meta-articles.json
cp -v ./4.0/it-it/meta-home.json        ./_data/4-0-it-it-meta-home.json
cp -v ./4.0/it-it/meta-topics.json      ./_data/4-0-it-it-meta-topics.json
cp -v ./4.0/it-it/meta-articles.json    ./_data/4-0-it-it-meta-articles.json
cp -v ./4.0/ja/meta-home.json           ./_data/4-0-ja-meta-home.json
cp -v ./4.0/ja/meta-topics.json         ./_data/4-0-ja-meta-topics.json
cp -v ./4.0/ja/meta-articles.json       ./_data/4-0-ja-meta-articles.json
cp -v ./4.0/pt/meta-home.json           ./_data/4-0-pt-meta-home.json
cp -v ./4.0/pt/meta-topics.json         ./_data/4-0-pt-meta-topics.json
cp -v ./4.0/pt/meta-articles.json       ./_data/4-0-pt-meta-articles.json
cp -v ./4.0/ro/meta-home.json           ./_data/4-0-ro-meta-home.json
cp -v ./4.0/ro/meta-topics.json         ./_data/4-0-ro-meta-topics.json
cp -v ./4.0/ro/meta-articles.json       ./_data/4-0-ro-meta-articles.json
cp -v ./4.0/ru/meta-home.json           ./_data/4-0-ru-meta-home.json
cp -v ./4.0/ru/meta-topics.json         ./_data/4-0-ru-meta-topics.json
cp -v ./4.0/ru/meta-articles.json       ./_data/4-0-ru-meta-articles.json
cp -v ./4.0/th/meta-home.json           ./_data/4-0-th-meta-home.json
cp -v ./4.0/th/meta-topics.json         ./_data/4-0-th-meta-topics.json
cp -v ./4.0/th/meta-articles.json       ./_data/4-0-th-meta-articles.json
cp -v ./4.0/tl/meta-home.json           ./_data/4-0-tl-meta-home.json
cp -v ./4.0/tl/meta-topics.json         ./_data/4-0-tl-meta-topics.json
cp -v ./4.0/tl/meta-articles.json       ./_data/4-0-tl-meta-articles.json
cp -v ./4.0/tr/meta-home.json           ./_data/4-0-tr-meta-home.json
cp -v ./4.0/tr/meta-topics.json         ./_data/4-0-tr-meta-topics.json
cp -v ./4.0/tr/meta-articles.json       ./_data/4-0-tr-meta-articles.json
cp -v ./4.0/uk/meta-home.json           ./_data/4-0-uk-meta-home.json
cp -v ./4.0/uk/meta-topics.json         ./_data/4-0-uk-meta-topics.json
cp -v ./4.0/uk/meta-articles.json       ./_data/4-0-uk-meta-articles.json
cp -v ./4.0/zh-cn/meta-home.json        ./_data/4-0-zh-cn-meta-home.json
cp -v ./4.0/zh-cn/meta-topics.json      ./_data/4-0-zh-cn-meta-topics.json
cp -v ./4.0/zh-cn/meta-articles.json    ./_data/4-0-zh-cn-meta-articles.json


cp -v ./3.1/en/meta-home.json           ./_data/3-1-en-meta-home.json
cp -v ./3.1/en/meta-topics.json         ./_data/3-1-en-meta-topics.json
cp -v ./3.1/en/meta-articles.json       ./_data/3-1-en-meta-articles.json

cp -v ./3.2/en/meta-home.json           ./_data/3-2-en-meta-home.json
cp -v ./3.2/en/meta-topics.json         ./_data/3-2-en-meta-topics.json
cp -v ./3.2/en/meta-articles.json       ./_data/3-2-en-meta-articles.json

cp -v ./3.3/en/meta-home.json           ./_data/3.3-en-meta-home.json
cp -v ./3.3/en/meta-topics.json         ./_data/3.3-en-meta-topics.json
cp -v ./3.3/en/meta-articles.json       ./_data/3.3-en-meta-articles.json

cp -v ./3.4/cs-cz/meta-home.json        ./_data/3-4-cs-cz-meta-home.json
cp -v ./3.4/cs-cz/meta-topics.json      ./_data/3-4-cs-cz-meta-topics.json
cp -v ./3.4/cs-cz/meta-articles.json    ./_data/3-4-cs-cz-meta-articles.json
cp -v ./3.4/de-de/meta-home.json        ./_data/3-4-de-de-meta-home.json
cp -v ./3.4/de-de/meta-topics.json      ./_data/3-4-de-de-meta-topics.json
cp -v ./3.4/de-de/meta-articles.json    ./_data/3-4-de-de-meta-articles.json
cp -v ./3.4/en/meta-home.json           ./_data/3-4-en-meta-home.json
cp -v ./3.4/en/meta-topics.json         ./_data/3-4-en-meta-topics.json
cp -v ./3.4/en/meta-articles.json       ./_data/3-4-en-meta-articles.json
cp -v ./3.4/es-es/meta-home.json        ./_data/3-4-es-es-meta-home.json
cp -v ./3.4/es-es/meta-topics.json      ./_data/3-4-es-es-meta-topics.json
cp -v ./3.4/es-es/meta-articles.json    ./_data/3-4-es-es-meta-articles.json
cp -v ./3.4/fa-ir/meta-home.json        ./_data/3-4-fa-ir-meta-home.json
cp -v ./3.4/fa-ir/meta-topics.json      ./_data/3-4-fa-ir-meta-topics.json
cp -v ./3.4/fa-ir/meta-articles.json    ./_data/3-4-fa-ir-meta-articles.json
cp -v ./3.4/fr-fr/meta-home.json        ./_data/3-4-fr-fr-meta-home.json
cp -v ./3.4/fr-fr/meta-topics.json      ./_data/3-4-fr-fr-meta-topics.json
cp -v ./3.4/fr-fr/meta-articles.json    ./_data/3-4-fr-fr-meta-articles.json
cp -v ./3.4/id-id/meta-home.json        ./_data/3-4-id-id-meta-home.json
cp -v ./3.4/id-id/meta-topics.json      ./_data/3-4-id-id-meta-topics.json
cp -v ./3.4/id-id/meta-articles.json    ./_data/3-4-id-id-meta-articles.json
cp -v ./3.4/it-it/meta-home.json        ./_data/3-4-it-it-meta-home.json
cp -v ./3.4/it-it/meta-topics.json      ./_data/3-4-it-it-meta-topics.json
cp -v ./3.4/it-it/meta-articles.json    ./_data/3-4-it-it-meta-articles.json
cp -v ./3.4/ja-jp/meta-home.json        ./_data/3-4-ja-jp-meta-home.json
cp -v ./3.4/ja-jp/meta-topics.json      ./_data/3-4-ja-jp-meta-topics.json
cp -v ./3.4/ja-jp/meta-articles.json    ./_data/3-4-ja-jp-meta-articles.json
cp -v ./3.4/pl-pl/meta-home.json        ./_data/3-4-pl-pl-meta-home.json
cp -v ./3.4/pl-pl/meta-topics.json      ./_data/3-4-pl-pl-meta-topics.json
cp -v ./3.4/pl-pl/meta-articles.json    ./_data/3-4-pl-pl-meta-articles.json
cp -v ./3.4/ru-ru/meta-home.json        ./_data/3-4-ru-ru-meta-home.json
cp -v ./3.4/ru-ru/meta-topics.json      ./_data/3-4-ru-ru-meta-topics.json
cp -v ./3.4/ru-ru/meta-articles.json    ./_data/3-4-ru-ru-meta-articles.json
cp -v ./3.4/tr-tr/meta-home.json        ./_data/3-4-tr-tr-meta-home.json
cp -v ./3.4/tr-tr/meta-topics.json      ./_data/3-4-tr-tr-meta-topics.json
cp -v ./3.4/tr-tr/meta-articles.json    ./_data/3-4-tr-tr-meta-articles.json
cp -v ./3.4/uk-ua/meta-home.json        ./_data/3-4-uk-ua-meta-home.json
cp -v ./3.4/uk-ua/meta-topics.json      ./_data/3-4-uk-ua-meta-topics.json
cp -v ./3.4/uk-ua/meta-articles.json    ./_data/3-4-uk-ua-meta-articles.json
cp -v ./3.4/zh-cn/meta-home.json        ./_data/3-4-zh-cn-meta-home.json
cp -v ./3.4/zh-cn/meta-topics.json      ./_data/3-4-zh-cn-meta-topics.json
cp -v ./3.4/zh-cn/meta-articles.json    ./_data/3-4-zh-cn-meta-articles.json

exit 0
