#!/usr/bin/env bash

cp -v ./4.0/cs-cz/meta-articles.json  ./_data/4-0-cs-cz-meta-articles.json
cp -v ./4.0/cs-cz/meta-home.json      ./_data/4-0-cs-cz-meta-home.json
cp -v ./4.0/cs-cz/meta-topics.json    ./_data/4-0-cs-cz-meta-topics.json
cp -v ./4.0/de-de/meta-articles.json  ./_data/4-0-de-de-meta-articles.json
cp -v ./4.0/de-de/meta-home.json      ./_data/4-0-de-de-meta-home.json
cp -v ./4.0/de-de/meta-topics.json    ./_data/4-0-de-de-meta-topics.json
cp -v ./4.0/el-gr/meta-articles.json  ./_data/4-0-el-gr-meta-articles.json
cp -v ./4.0/el-gr/meta-home.json      ./_data/4-0-el-gr-meta-home.json
cp -v ./4.0/el-gr/meta-topics.json    ./_data/4-0-el-gr-meta-topics.json
cp -v ./4.0/en/meta-articles.json     ./_data/4-0-en/meta-articles.json
cp -v ./4.0/en/meta-home.json         ./_data/4-0-en/meta-home.json
cp -v ./4.0/en/meta-topics.json       ./_data/4-0-en/meta-topics.json
cp -v ./4.0/es-es/meta-articles.json  ./_data/4-0-es-es-meta-articles.json
cp -v ./4.0/es-es/meta-home.json      ./_data/4-0-es-es-meta-home.json
cp -v ./4.0/es-es/meta-topics.json    ./_data/4-0-es-es-meta-topics.json
cp -v ./4.0/fa-ir/meta-articles.json  ./_data/4-0-fa-ir-meta-articles.json
cp -v ./4.0/fa-ir/meta-home.json      ./_data/4-0-fa-ir-meta-home.json
cp -v ./4.0/fa-ir/meta-topics.json    ./_data/4-0-fa-ir-meta-topics.json
cp -v ./4.0/fr-fr/meta-articles.json  ./_data/4-0-fr-fr-meta-articles.json
cp -v ./4.0/fr-fr/meta-home.json      ./_data/4-0-fr-fr-meta-home.json
cp -v ./4.0/fr-fr/meta-topics.json    ./_data/4-0-fr-fr-meta-topics.json
cp -v ./4.0/id-id/meta-articles.json  ./_data/4-0-id-id-meta-articles.json
cp -v ./4.0/id-id/meta-home.json      ./_data/4-0-id-id-meta-home.json
cp -v ./4.0/id-id/meta-topics.json    ./_data/4-0-id-id-meta-topics.json
cp -v ./4.0/it-it/meta-articles.json  ./_data/4-0-it-it-meta-articles.json
cp -v ./4.0/it-it/meta-home.json      ./_data/4-0-it-it-meta-home.json
cp -v ./4.0/it-it/meta-topics.json    ./_data/4-0-it-it-meta-topics.json
cp -v ./4.0/ja-jp/meta-articles.json  ./_data/4-0-ja-jp-meta-articles.json
cp -v ./4.0/ja-jp/meta-home.json      ./_data/4-0-ja-jp-meta-home.json
cp -v ./4.0/ja-jp/meta-topics.json    ./_data/4-0-ja-jp-meta-topics.json
cp -v ./4.0/pl-pl/meta-articles.json  ./_data/4-0-pl-pl-meta-articles.json
cp -v ./4.0/pl-pl/meta-home.json      ./_data/4-0-pl-pl-meta-home.json
cp -v ./4.0/pl-pl/meta-topics.json    ./_data/4-0-pl-pl-meta-topics.json
cp -v ./4.0/ru-ru/meta-articles.json  ./_data/4-0-ru-ru-meta-articles.json
cp -v ./4.0/ru-ru/meta-home.json      ./_data/4-0-ru-ru-meta-home.json
cp -v ./4.0/ru-ru/meta-topics.json    ./_data/4-0-ru-ru-meta-topics.json
cp -v ./4.0/tr-tr/meta-articles.json  ./_data/4-0-tr-tr-meta-articles.json
cp -v ./4.0/tr-tr/meta-home.json      ./_data/4-0-tr-tr-meta-home.json
cp -v ./4.0/tr-tr/meta-topics.json    ./_data/4-0-tr-tr-meta-topics.json
cp -v ./4.0/uk-ua/meta-articles.json  ./_data/4-0-uk-ua-meta-articles.json
cp -v ./4.0/uk-ua/meta-home.json      ./_data/4-0-uk-ua-meta-home.json
cp -v ./4.0/uk-ua/meta-topics.json    ./_data/4-0-uk-ua-meta-topics.json
cp -v ./4.0/zh-cn/meta-articles.json  ./_data/4-0-zh-cn-meta-articles.json
cp -v ./4.0/zh-cn/meta-home.json      ./_data/4-0-zh-cn-meta-home.json
cp -v ./4.0/zh-cn/meta-topics.json    ./_data/4-0-zh-cn-meta-topics.json
